# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
name: GSTService
version: 2.2.0
appVersion: 0.1.0
description: A Helm Chart for GST
home: https://github.com/brian-intel/automated-self-checkout/tree/kubernetesGST
icon: 
sources:
- https://github.com/brian-intel/automated-self-checkout/tree/kubernetesGST
engine: gotpl