Containers:
 - Name: GST
   DockerImage: dlstreamer:dev
   EnvironmentVariableFiles: yolov5-cpu.env
   Entrypoint: /script/entrypoint.sh --pipeline_script_choice yolov5s.sh
   Volumes: 
     - "./use-cases/dlstreamer/cl-cache:/home/pipeline-server/.cl-cache"
     - /tmp/.X11-unix:/tmp/.X11-unix
     - "./models:/home/pipeline-server/models"
     - "./results:/tmp/results"