apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f compose/docker-compose.yml convert -o kubernetes/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: camera-simulator0
  name: camera-simulator0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: camera-simulator0
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f compose/docker-compose.yml convert -o kubernetes/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: camera-simulator0
    spec:
      containers:
        - args:
            - -nostdin
            - -re
            - -stream_loop
            - "-1"
            - -i
            - /sample-media/coca-cola-4465029-1920-15-bench.mp4
            - -c
            - copy
            - -f
            - rtsp
            - -rtsp_transport
            - tcp
            - rtsp://camera-simulator:8554/camera_0
          command:
            - ffmpeg
          image: cam-sim:dev
          name: camera-simulator0
          resources: {}
      restartPolicy: Always
status: {}
