#
# Copyright (C) 2024 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#


 ## Current Developer Toolbox doesn't support environment files, make sure to remove any files or environment variables starting with $
version: '3.7'
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    ports:
      - "127.0.0.1:8554:8554"
  camera-simulator0:
    build:
      context: .
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator0
    network_mode: "host"
    entrypoint: ffmpeg
    command: "
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport
        tcp
        rtsp://localhost:8554/camera_0
        "
    depends_on:
      - camera-simulator
    volumes:
      - ${RETAIL_USE_CASE_ROOT:-../..}/performance-tools/sample-media:/home/pipeline-server/sample-media

  OvmsClientGrpcPython:
    image: grpc_python:dev
    deploy:
      mode: replicated
      replicas: ${PIPELINE_COUNT:-1}
    network_mode: "host"
    entrypoint: /app/entrypoint.sh --model_name ${MODEL_NAME:-instance-segmentation-security-1040}
    env_file:
      - ./res/grpc_python.env
    environment:
      - CONTAINER_NAME="grpc_python0"
      - GRPC_PORT=${GRPC_PORT:-9001}
      - GRPC_ADDRESS=${GRPC_ADDRESS:-localhost}
      - INPUTSRC=${INPUTSRC:-rtsp://localhost:8554/camera_0}
      - TARGET_DEVICE=${TARGET_DEVICE:-CPU}
      - OVMS_INIT_TIME_IN_SECOND=10
      - RENDER_MODE=0 #RENDER_MODE=1 will work only after running xhost +local:docker
      - DISPLAY=$DISPLAY
    volumes:
      - ${RESULTS_DIR:-./../results}:/tmp/results
      - ~/.Xauthority:/home/dlstreamer/.Xauthority
      - /tmp/.X11-unix
